name: Windows (Direct3D11)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Compile
      run: armorcore/Kinc/make --from armorcore -g direct3d11
